kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  storageClassName: mekom-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
